language: cpp

os: windows

compiler: cl

env:
  global:
    - BOOST_ROOT="C:\local\boost_1_67_0"
    - BOOST_LIBRARYDIR="C:\local\boost_1_67_0\lib64-msvc-14.1"

before_script:
  - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
  - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\VsDevCmd.bat" -test
  - git clone https://github.com/google/googletest.git
  - cd googletest && cmake -DCMAKE_INSTALL_PREFIX=install .
  - cmake --build . --target install
  - cd ..
  - choco install boost-msvc-14.1
  #- dir "C:\Boost"
  #- dir "C:\local\boost_1_67_0\libs\context"

script:
  - cmake -DCMAKE-BUILD_TYPE=Debug -DQUANTUM_ENABLE_TESTS=ON -DCMAKE_INSTALL_PREFIX=tests -DGTEST_ROOT=googletest/install .
  - cmake --build . --target all && ctest -C Debug
